### ISSUE TITLE
Decimal to JS with arbitrary precision

### ISSUE THREAD

**Issue by ronnybremer** [RReverser/serde-wasm-bindgen#66]
A Decimal in a struct will be converted into a String by default:
```rust
#[derive(Debug, Serialize, Deserialize, PartialEq, Clone)]
struct Test {
   pub the_dec: Decimal,
}
```
with the_dev set to 10.01 would lead to:
```js
the_dec: "10.01"
```

I tried to use the arbitrary precision option, but this got worse:
```rust
#[derive(Debug, Serialize, Deserialize, PartialEq, Clone)]
struct Test {
    #[serde(with = "rust_decimal::serde::arbitrary_precision")]
   pub the_dec: Decimal,
}
```

```js
the_dec: {$serde_json::private::Number: "10.01"}
```

My current workaround is to use float:
```rust
#[derive(Debug, Serialize, Deserialize, PartialEq, Clone)]
struct Test {
    #[serde(with = "rust_decimal::serde::float")]
   pub the_dec: Decimal,
}
```

```js
the_dec: 10.01
```
which works great, however, if the_dec is set to 10.10, it will convert to
```js
the_dec: 10.1
```
loosing the precision in the process. Especially for fixed precision amounts like currency this will lead to some confusion when displayed.

From the rust_decimal serde documentation https://docs.rs/rust_decimal/latest/rust_decimal/index.html#serde-with-arbitrary-precision the `arbitrary_precision` option is mostly used for Json conversion, however, would it somehow be possible to also support it in here so the last example would lead to:
```js
the_dec: 10.10
```

**Comment by RReverser** [comment]
> which works great, however, if the_dec is set to 10.10, it will convert to
> 
> ```js
> the_dec: 10.1
> ```
> 
> loosing the precision in the process

I don't see how that's losing precision. In floating-point representation those are the same numbers, just different printing formats. If you're using `console.log`, it just automatically prints number without trailing zeros, but you can always use `console.log(num.toFixed(2))` if you want to print e.g. 2 fixed digits after the dot.

As a more general solution, if you want to convert decimal numbers to string instead of float, you can probably use something like [`serde_with::DisplayFromStr`](https://docs.rs/serde_with/3.8.1/serde_with/struct.DisplayFromStr.html).

**Comment by ronnybremer** [comment]
> I don't see how that's losing precision.
So it will end up within JS shortened anyway, understood. Thank you @RReverser
